# Generated by Django 3.0.8 on 2020-08-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200823_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='category',
            field=models.CharField(default='밥집', max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='downinfo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='mainpic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='menupic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='resnumber',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='respic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='upinfo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='xco',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='yco',
            field=models.FloatField(max_length=20),
        ),
    ]
